---
title: "Data Preparation"
author: "Mayank Goel"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-1.csv"))
head(df)
```


```{r}
head(df,20)
aggregate(speed_mph_mean ~ utc_timestamp, df, mean)
```


```{r}
library(sqldf)
jan = sqldf('SELECT year, month, day , AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
```



```{r}
write.csv(jan, here("Data","2019-Jan-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-2.csv"))
```

```{r}
head(df)
```


```{r}

month = sqldf('SELECT year, month, day, utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Feb-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-3.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Mar-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-4.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Apr-Daily-Aggregated.csv"))
```


```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-5.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-May-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-6.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Jun-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-7.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Jul-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-8.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Aug-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-9.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Sep-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-10.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Jun-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-6.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Jun-Daily-Aggregated.csv"))
```

```{r}
library(sqldf)
library(here)
df = read.csv(here("Data","movement-speeds-hourly-seattle-2019-6.csv"))
head(df)
```

```{r}
month = sqldf('SELECT year, month, day , utc_timestamp, AVG(speed_mph_mean) AS speed_mph_mean, AVG(speed_mph_stddev) AS speed_mph_stddev FROM df GROUP BY month, day')
write.csv(month, here("Data","2019-Jun-Daily-Aggregated.csv"))
```
